[package]
name = "treehouse"
version = "0.1.0"
edition = "2021"

[lib]
name = "treehouse"
path = "src/lib/mod.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
serde = { version = "1.0.188", features = ["serde_derive"] }
serde_json = "1.0.107"
